# roles/db/tasks/install_mongo.yml
---
- name: Install mongodb package
  apt:
    name: mongodb
    state: present
  tags: install

- name: Enable mongodb service
  systemd:
    name: mongodb
    enabled: yes
  tags: install
