- name: Prepare app host
  hosts: app
  become: true
  roles:
    - app
    - role: jdauphant.nginx
      nginx_sites:
        default:
          - "listen 80"
          - "location / { proxy_pass http://127.0.0.1:9292; }"
