- name: Install python for all hosts
  hosts: all
  become: true
  tasks:
    - name: Install python package
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
