---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: "0600"
  notify: reload puma

- name: Add config for db connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    group: "{{ deploy_user }}"
    owner: "{{ deploy_user }}"
    mode: "0644"
  notify: reload puma

- name: Enable puma
  systemd: name=puma enabled=yes
