- name: Prepare app host
  hosts: app
  become: true
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: "Reload puma"

    - name: Enable puma
      systemd: name=puma enabled=yes

    - name: Add config for db connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        group: appuser
        owner: appuser
      notify: "Reload puma"

  handlers:
    - name: "Reload puma"
      systemd: name=puma state=restarted
