#
# One play
#

- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 192.168.10.6
  tasks: 
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        # Different path for mongodb package
        dest: /etc/mongodb.conf
        mode: 0644
      notify: "Restart mongodb"
      tags: db-tag
    #
    #
    #
    - name: Install git
      become: true
      apt:
        name: git
        state: present
      tags: app-tag
    - name: Fetch application repo
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/appuser/reddit'
        version: monolith
      notify: "Reload puma"
      tags: app-tag

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/appuser/reddit'
      tags: app-tag

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: "Reload puma"
      tags: app-tag

    - name: Enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Add config for db connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag

  handlers:
    - name: "Restart mongodb"
      become: true
      service: name=mongodb state=restarted

    - name: "Reload puma"
      become: true
      systemd: name=puma state=restarted

