name: Run tests for devops course
on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Run tests
      run: curl -s https://gist.githubusercontent.com/kaineer/193012aeaa5427d2572b15c92423b5bb/raw/c724f3f082195fe542955ef056248b4b8fcdf62d/run.sh | bash
